name:                madlib
version:             0.12.2
github:              "madlib-lang/madlib"
license:             BSD3
author:              "Arnaud Boeglin, Brekk Bockrath"
maintainer:          "fpopensorcerers@gmail.com"
copyright:           "2021 Arnaud Boeglin, 2021 Brekk Bockrath"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/madlib-lang/madlib#readme>

dependencies:
- base >= 4.7 && < 5
- pretty-show
- array >= 0.5.4.0
- containers >= 0.6.2.1
- hpc-lcov
- mtl
- transformers
- exceptions
- either
- filepath
- hspec
- hspec-golden
- text
- optparse-applicative >= 0.16.1.0
- directory == 1.3.6.0
- aeson >= 1.5.6.0
- bytestring
- MissingH >= 1.4.3.0
- executable-path >= 0.0.3.1
- regex-tdfa
- process >= 1.6.9.0
- ansi-wl-pprint >= 0.6.9
- utf8-string
- process-extras
- groupBy
- cryptohash-md5
- aeson-pretty
- Glob >= 0.10.2
- prettyprinter >= 1.6.2
- parallel-io == 0.3.5
- Cabal == 3.6.2.0
- rock == 0.3.*
- dependent-sum-template == 0.1.*
- some == 1.*
- hashable
- template-haskell

_exe-defs: &exe-defaults
  ghc-options:
    - -threaded
    - -funbox-strict-fields
    - -O2
    - -optc-O2

executables:
  madlib:
    <<: *exe-defaults
    main: Main.hs
    source-dirs: src
    dependencies:
      - madlib
    when:
    - condition: flag(static)
      ld-options: -static

library:
  dependencies:
    - llvm-hs == 9.0.1
    - llvm-hs-pure == 9.0.0
    - llvm-hs-pretty == 0.9.0.0
    - compiler-common
    # - query
  source-dirs: compiler

internal-libraries:
  # query:
  #   source-dirs: query
  #   dependencies:
  #     - compiler-common
  compiler-common:
    source-dirs: compiler-common
    dependencies:
      - llvm-hs-pure == 9.0.0

tests:
  madlib-test:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec >= 2.7.2
      - query
      - madlib
      - compiler-common

flags:
  static:
    description: Pass -static to ghc.
    manual: true
    default: false
