name:                madlib
version:             0.0.8
github:              "open-sorcerers/madlib"
license:             BSD3
author:              "Arnaud Boeglin, Brekk Bockrath"
maintainer:          "fpopensorcerers@gmail.com"
copyright:           "2020 Arnaud Boeglin, 2020 Brekk Bockrath"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/madlib#readme>

dependencies:
- base >= 4.7 && < 5
- pretty-show
- array == 0.5.4.0
- containers == 0.6.2.1
- hpc-lcov
- mtl
- brittany
- transformers
- exceptions
- either
- filepath
- hspec
- hspec-golden
- text
- optparse-applicative
- directory == 1.3.6.0
- aeson
- bytestring
- MissingH
- executable-path == 0.0.3.1
- regex-tdfa
- process == 1.6.9.0
- ansi-wl-pprint == 0.6.9

library:
  source-dirs: src

_exe-defs: &exe-defaults
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  

executables:
  madlib:
    <<: *exe-defaults
    main:                Main.hs
    source-dirs: src
      
tests:
  madlib-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - hspec == 2.7.2
      - madlib

