#!/bin/bash

if [ "$1" == "watch" ]
then
  stack build --test --no-run-tests;
  # this is needed as the runtime must be located next to the madlib executable
  cp -R runtime "$(stack path --dist-dir)/build/madlib-test/"

  stack build --test --file-watch --fast;
elif [ "$1" == "coverage" ]
then
  stack build --test --coverage --no-run-tests
  # this is needed as the runtime must be located next to the madlib executable
  cp -R runtime "$(stack path --dist-dir)/build/madlib-test/"

  stack build --test --coverage && stack hpc report .;
elif [ "$1" == "integration" ]
then
  madlib test -i integration-tests
  madlib test --target llvm -i integration-tests
elif [ -z "$1" ]
then
  stack build --test --no-run-tests;
  # this is needed as the runtime must be located next to the madlib executable
  cp -R runtime "$(stack path --dist-dir)/build/madlib-test/"

  stack build --test;
else
  echo "'$1' is not a valid option.\nvalid options:\n  * watch\n  * coverage"
fi