on: [push]
name: build
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install haskell
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
          ~/.ghcup/bin/ghcup install 8.10.7
          ~/.ghcup/bin/ghcup install cabal 3.4.0.0
          ~/.ghcup/bin/ghcup install stack 2.7.3
          ~/.ghcup/bin/ghcup set 8.10.7
          ~/.ghcup/bin/ghcup set cabal 3.4.0.0
          ~/.ghcup/bin/ghcup set stack 2.7.3

      - name: Configure stack
        run: stack config set system-ghc --global true

      - run: sudo apt-get update -y

      - run: sudo apt-get install -y lcov llvm-9 nasm
      # - run: DEBIAN_FRONTEND=noninteractive sudo apt-get install -y curl llvm-9 zip wget automake libtool clang gcc-9 g++-9 libstdc++-9-dev libc++abi-9-dev unzip musl-tools cmake git nasm libssl-dev
      # - run: sudo apt-get install -y build-essential curl libffi-dev libffi7 libgmp-dev libgmp10 libncurses-dev libncurses5 libtinfo5

      - uses: actions/cache@v2.1.3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-8.10.7-stack

      - run: stack install alex happy

      - name: build runtime libs
        run: TARGET="LINUX_X64" ./scripts/build-runtime-libs

      - name: build runtime
        run: AR="llvm-ar-9" TARGET="LINUX_X64" CPLUS_INCLUDE_PATH="/usr/include/c++/9:/usr/include/x86_64-linux-gnu/c++/9:/usr/include/" ./scripts/build-runtime

      - run: ./scripts/test coverage

      - run: ./scripts/coverage

      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage/codecov.json
          # flags: unittests # optional
          # name: codecov-umbrella # optional
          # fail_ci_if_error: true # optional (default = false)
          verbose: true

      # - name: Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     path-to-lcov: coverage/lcov.info
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
