on: [push]
name: build
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-haskell@v1.1.3
        with:
          ghc-version: "8.10.7"
          cabal-version: "3.4.0.0"
          enable-stack: true
          stack-version: "2.7.3"

      - name: Configure stack
        run: stack config set system-ghc --global true

      - run: sudo apt-get update -y

      - run: sudo apt-get install -y lcov llvm-9

      - uses: actions/cache@v2.1.3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-8.10.7-stack

      - run: stack install alex happy

      - run: ./scripts/test coverage

      - run: ./scripts/coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
