name: 'Build linux target for release'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release ( ex: v0.0.1 )'
        required: true

env:
  node-version: 20.x

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: "20.10"
          docker_channel: stable

      - name: Build madlib
        run: DOCKER_BUILDKIT=1 docker build -f ".github/workflows/Dockerfile-x86_64-linux" -o . .

      - name: Bundle unknown archive
        run: |
          mkdir madlib-x86_64-unknown-linux-gnu
          cp ./madlib ./madlib-x86_64-unknown-linux-gnu/
          cp -R runtime ./madlib-x86_64-unknown-linux-gnu/
          cp -R prelude ./madlib-x86_64-unknown-linux-gnu/
          cp ./package-installer.js ./madlib-x86_64-unknown-linux-gnu/
          tar -czvf madlib-x86_64-unknown-linux-gnu.tar.gz madlib-x86_64-unknown-linux-gnu

      - name: Upload unknown build
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: ./madlib-x86_64-unknown-linux-gnu.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
